application: "azuread"
connectedSystemConfigs:
  - connectedSystemName: "<<AZUREAD_CONNECTED_SYSTEM_NAME_1>>"
    authenticationDetail:
      scheme: "https"
      host: "<<AZUREAD_AUTH_API_HOST_1>>"
      path: "/idmconnector.onmicrosoft.com/oauth2/v2.0/token"
      method: "POST"
      grantType: "client_credentials"
      scope: "https://graph.microsoft.com/.default"
      proxyHost: "<<PROXY_HOST_1>>"
      proxyPort: "<<PROXY_PORT_1>>"
      clientCode: "<<CLIENT_CODE_1>>"
      clientSecret: "<<CLIENT_SECRET_1>>"
    applicationInstanceDetail:
      scheme: "https"
      host: "<<AZUREAD_API_HOST_1>>"
  - connectedSystemName: "<<AZUREAD_CONNECTED_SYSTEM_NAME_2>>"
    authenticationDetail:
      scheme: "https"
      host: "<<AZUREAD_AUTH_API_HOST_2>>"
      path: "/idmconnector.onmicrosoft.com/oauth2/v2.0/token"
      method: "POST"
      grantType: "client_credentials"
      scope: "https://graph.microsoft.com/.default"
      proxyHost: "<<PROXY_HOST_2>>"
      proxyPort: "<<PROXY_PORT_2>>"
      clientCode: "<<CLIENT_CODE_2>>"
      clientSecret: "<<CLIENT_SECRET_2>>"
    applicationInstanceDetail:
      scheme: "https"
      host: "<<AZUREAD_API_HOST_2>>"
  - connectedSystemName: "<<AZUREAD_CONNECTED_SYSTEM_NAME_3>>"
    authenticationDetail:
      scheme: "https"
      host: "<<AZUREAD_AUTH_API_HOST_3>>"
      path: "/idmconnector.onmicrosoft.com/oauth2/v2.0/token"
      method: "POST"
      grantType: "client_credentials"
      scope: "https://graph.microsoft.com/.default"
      proxyHost: "<<PROXY_HOST_3>>"
      proxyPort: "<<PROXY_PORT_3>>"
      clientCode: "<<CLIENT_CODE_3>>"
      clientSecret: "<<CLIENT_SECRET_3>>"
    applicationInstanceDetail:
      scheme: "https"
      host: "<<AZUREAD_API_HOST_3>>"